# Generated by Django 4.0.2 on 2023-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
