# Generated by Django 4.0.2 on 2023-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_test_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='testname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
