# Generated by Django 4.0.2 on 2023-11-22 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usertest_feedback_usertest_grade_usertest_testname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
