# Generated by Django 4.0.2 on 2023-11-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usertest_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='timestamp',
        ),
    ]
