# Generated by Django 4.0.2 on 2023-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usertest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='time_secs',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
