# Generated by Django 4.0.2 on 2023-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usertest_time_secs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='assignNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
