# Generated by Django 4.0.2 on 2023-11-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userassignment_assignno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
    ]
