# Generated by Django 4.0.2 on 2023-11-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usertest_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='time_secs',
        ),
    ]
