# Generated by Django 4.0.2 on 2023-11-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_usertest_time_secs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertest',
            old_name='submitted',
            new_name='opened',
        ),
    ]
